networks:
  test:
    name: sample

volumes:
  namedvolume:
    
services:
  mycontainer:
   container_name: mycontainer
   image: myimage:1.0
   networks:
      test:
        
  container1:
    container_name: couchdb
    image: hyperledger/fabric-couchdb
    environment:
      - COUCHDB_USER=user
      - COUCHDB_PASSWORD=password
    ports:
      - 3000:5984
    networks:
      test:
        
  container2:
    container_name: test1
    image: hyperledger/fabric-tools:2.5
    tty: true
    volumes:
      - ./samplefolder:/hyperledger/fabric/newfolder
      - namedvolume:/hyperledger/fabric
    working_dir: /hyperledger/fabric
    ports:
      - 7050:7050
    networks:
      test:

  
